server:
  port: 8090
  
spring:
  application:
    name: 'empresa-pix'
  greeting: 'changeit'
 
springdoc:
  swagger-ui:
    query-config-enabled: true 
    use-root-path: true 
  packagesToScan: 'com.empresa.immediate.controller'
  pathsToMatch: '/**'