server:
  port: 8080
  
spring:
  application:
    name: 'batch-bacen-empresa-ifusp'
  greeting: 'changeit'
 
springdoc:
  swagger-ui:
    query-config-enabled: true 
    use-root-path: true 
  packagesToScan: 'com.ifusp.empresa.batch.web'
  pathsToMatch: '/**'